name = "HashCode2014"
uuid = "7bbed249-721d-42ac-b1f6-7cf884be0fbe"
authors = ["Guillaume Dalle <22795598+gdalle@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
CondaPkg = "0.2"
ProgressLogging = "0.1"
PythonCall = "0.9"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
